code refactoring and fixes
umar0932/bnb-web pull request #1
Opened 2023-10-25 12:01 UTC by aitezazimtiaz

2023-10-26 05:00 UTC, umar0932 commented on .husky/pre-commit
> +npm run lint
add end of line

2023-10-26 05:01 UTC, umar0932 commented on src/components/AutoComplete/AutoCompleteAcc.tsx
Sort above imports in lexical order

2023-10-26 05:04 UTC, umar0932 commented on src/components/Cards/FollowCard.tsx
>  }
move all the interfaces in a separate file

2023-10-26 05:04 UTC, umar0932 commented on src/components/Cards/OrderCard.tsx
>  export default function OrderCard() {
make it arrow function and give space above

2023-10-26 05:05 UTC, umar0932 commented on src/components/Checkout/Checkout.tsx
> +          clearInterval(Ref.current as number) // Cast to number
remove brackets and make it a single line

2023-10-26 05:08 UTC, umar0932 commented on src/components/Forms/AccountSettingsForm/ChangeEmailForm.tsx
> +  })
remove brackets

2023-10-26 05:09 UTC, umar0932 commented on src/components/Forms/AccountSettingsForm/ChangePasswordForm.tsx
> +    }
remove brackets

2023-10-26 05:11 UTC, umar0932 commented on src/components/Forms/AccountSettingsForm/EmailPreferanceForm.tsx
>  export default function EmailPreferanceForm() {
make an arrow function every where

2023-10-26 05:13 UTC, umar0932 commented on src/components/Forms/BasicInfoForm.tsx
>    // const [TagCharCount, setTagCharCount] = useState(0);
remove comments

2023-10-26 05:13 UTC, umar0932 commented on src/components/Forms/BasicInfoForm.tsx
>    // const [tags, setTags] = useState([]);
remove comment

2023-10-26 05:13 UTC, umar0932 commented on src/components/Forms/BasicInfoForm.tsx
>    //   const tagValue = e.target.value;
remove comment

2023-10-26 05:14 UTC, umar0932 commented on src/components/Forms/BasicInfoForm.tsx
>                </div>
make a separate component for input and import it from there

2023-10-26 05:16 UTC, umar0932 commented on src/components/Forms/BasicInfoForm.tsx
>                      options={options}
remove comment

2023-10-26 05:16 UTC, umar0932 commented on src/components/Forms/BasicInfoForm.tsx
> +                      control: (baseStyles) => ({
remove brackets

2023-10-26 05:17 UTC, umar0932 commented on src/components/Forms/CheckoutForm.tsx
> +    }
remove brackets

2023-10-26 05:17 UTC, umar0932 commented on src/components/Forms/CheckoutForm.tsx
>                  >
make a separate component for label

2023-10-26 05:18 UTC, umar0932 commented on src/components/Forms/CheckoutForm.tsx
> -                  />
make a separate component for image

2023-10-26 05:18 UTC, umar0932 commented on src/components/Forms/CheckoutForm.tsx
> +                  className='h-[20px] w-[20px] border-btnprimary bg-white text-btnprimary'
make a separate component for RadioGroupItem

2023-10-26 05:19 UTC, umar0932 commented on src/components/Forms/CheckoutForm.tsx
>                <Checkbox defaultChecked={true} />
make separate component of checkbox

2023-10-26 05:20 UTC, umar0932 commented on src/components/Forms/CheckoutForm.tsx
>          {/* Right Side */}
remove comment

2023-10-26 05:20 UTC, umar0932 commented on src/components/Forms/ContactSalesForm.tsx
>            {/* First and Last Name */}
remove comment

2023-10-26 05:21 UTC, umar0932 commented on src/components/Forms/ContactSalesForm.tsx
>              <input
use custom Input component everywhere

2023-10-26 05:22 UTC, umar0932 commented on src/components/Forms/ContactSalesForm.tsx
>              </Select>
make a separate component for select

2023-10-26 05:23 UTC, umar0932 commented on src/components/Forms/DateTimeForm.tsx
>    const buttonStyles = (buttonName: any) => {
remove brackets

2023-10-26 05:23 UTC, umar0932 commented on src/components/Forms/DateTimeForm.tsx
>                </button>
make separate button component everywhere

2023-10-26 05:24 UTC, umar0932 commented on src/components/Forms/GeneralInfoForm.tsx
> -        <form
make separate form component

2023-10-26 05:25 UTC, umar0932 commented on src/components/Forms/OrganizerProfileForm.tsx
>            </Link>
make Link component separate

2023-10-26 05:26 UTC, umar0932 commented on src/components/HomePage/InterestsDialog.tsx
>    const handleClose = () => {
remove brackets

2023-10-26 08:32 UTC, umar0932 requested changes

2023-10-26 08:32 UTC, umar0932 commented on src/components/Cards/EventCard.tsx
> -  };
remove brackets

2023-10-26 08:32 UTC, umar0932 commented on src/components/Forms/AccountSettingsForm/PaymentCardForm.tsx
>    const formatCardNumber = (input: any) => {
remove bracket

2023-11-01 06:00 UTC, aitezazimtiaz commented on src/components/Forms/AccountSettingsForm/ChangeEmailForm.tsx
> +  })
error on removing brackets

2023-11-01 06:24 UTC, umar0932 approved these changes

2023-11-01 06:25 UTC, merged